# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2968e4a20f77338dd50191456efe2685fbe372a52ac348e1b180df7cc9e3e28c78983bc21d4070540dbbfd2afb0a95c69fe4134431ecce37f6d3b3a4ab5f5787

test:
  secret_key_base: 49ee673b104340d4730710b9266c03afd95c23651ad79e29fa66272da5fcde77bf6df6cbebc3780d851400d3ae4c12c715a211453424206017af3985295eafff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
